version: '3'

volumes:
  postgres_volume:
  prometheus_data:
  grafana_data:

services:
  pg-auth:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    depends_on:
      - pg-auth
    volumes:
      - ./migrations:/root/migrations
    environment:
      - DB_HOST=pg-auth_v1
      - MIGRATION_DIR=/root/migrations

  prometheus:
    image: prom/prometheus:v2.45.6
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus


  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana


  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"    # Web UI
      - "14250:14250"    # Collector gRPC
      - "14268:14268"    # Collector HTTP
      - "6831:6831/udp"  # Agent UDP (Jaeger thrift)
      - "6832:6832/udp"  # Agent UDP (TChannel)
      - "5778:5778"      # Agent HTTP